/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package calculadora;

/**
 *
 * @author abarrime
 */
public class CalculadoraView extends javax.swing.JFrame {

    /**
     * Creates new form CalculadoraView
     */
    public CalculadoraView() {
        initComponents();
        this.setTitle("Calculadora");
        this.setLocationRelativeTo(null);
        this.setExtendedState(3);
    }

    double num1 = 0;
    double num2 = 0;
    double resultado = 0;
    String operador = "";

    private double operaciones(double nu1, double nu2, String ope) {
        switch (ope) {
            case "+":
                resultado = nu1 + nu2;
                break;

            case "-":
                resultado = nu1 - nu2;
                break;

            case "*":
                resultado = nu1 * nu2;
                break;

            case "/":
                if (nu2 != 0) {
                    resultado = nu1 / nu2;
                } else {
                    jTnumeros.setText("Error dividir por 0");
                }
                break;

            default:

                break;
        }
        return resultado;
    }

    //Buscar punto
    private boolean buscarPunto(String cajaTexto) {
        boolean punto = false;
        for (int i = 0; i < cajaTexto.length(); i++) {
            if (cajaTexto.substring(i, i + 1).equals(".")) {
                punto = true;
                break;
            }
        }
        return punto;

    }

    private void sumar() {
        if (!jTnumeros.getText().equals("")) {
            num1 = Double.parseDouble(jTnumeros.getText());
            operador = "+";
            jTnumeros.setText("");
        }
    }

    private void restar() {
        if (!jTnumeros.getText().equals("")) {
            num1 = Double.parseDouble(jTnumeros.getText());
            operador = "-";
            jTnumeros.setText("");
        }
    }

    private void multiplicar() {
        if (!jTnumeros.getText().equals("")) {
            num1 = Double.parseDouble(jTnumeros.getText());
            operador = "*";
            jTnumeros.setText("");
        }
    }

    private void dividir() {
        if (!jTnumeros.getText().equals("")) {
            num1 = Double.parseDouble(jTnumeros.getText());
            operador = "/";
            jTnumeros.setText("");
        }
    }

    private void puntoDecimal() {
        if (jTnumeros.getText().equals("")) {
            jTnumeros.setText("0.");
        } else {
            if (!buscarPunto(jTnumeros.getText())) {
                jTnumeros.setText(jTnumeros.getText() + ".");
            }
        }
    }

    private void limpiarTodo() {
        jTnumeros.setText("");
        num1 = 0;
        num2 = 0;
        resultado = 0;
        operador = "";
    }
    
    private void limpiar(){
        if(jTnumeros.getText().length() > 0){
            String caja = jTnumeros.getText().substring(0, jTnumeros.getText().length() - 1);
            jTnumeros.setText(caja);
        }
    }

    private void igual() {
        if (!jTnumeros.getText().equals("")) {
            num2 = Double.parseDouble(jTnumeros.getText());
            if (num2 == 0 && operador.equals("/")) {
                jTnumeros.setText("Error dividir por 0");
            } else {
                if (num1 != 0 && !operador.equals("")) {
                    //Realizo la operación matemática
                    operaciones(num1, num2, operador);
                    //Muestro el resultado obtenido en el método
                    //Con String.valueOf convierto a String el objeto a mostrar
                    jTnumeros.setText(String.valueOf(resultado));
                }
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton19 = new javax.swing.JButton();
        jTnumeros = new javax.swing.JTextField();
        jBC = new javax.swing.JButton();
        jBCE = new javax.swing.JButton();
        jB1 = new javax.swing.JButton();
        jB2 = new javax.swing.JButton();
        jB3 = new javax.swing.JButton();
        jB4 = new javax.swing.JButton();
        jB5 = new javax.swing.JButton();
        jB6 = new javax.swing.JButton();
        jB7 = new javax.swing.JButton();
        jB8 = new javax.swing.JButton();
        jB9 = new javax.swing.JButton();
        jB0 = new javax.swing.JButton();
        jBDividir = new javax.swing.JButton();
        jBPuntoDecimal = new javax.swing.JButton();
        jBIgual = new javax.swing.JButton();
        jBSumar = new javax.swing.JButton();
        jBMultiplicar = new javax.swing.JButton();
        jBRestar = new javax.swing.JButton();

        jButton19.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTnumeros.setEditable(false);
        getContentPane().add(jTnumeros, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 27, 330, 35));

        jBC.setText("C");
        jBC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCActionPerformed(evt);
            }
        });
        getContentPane().add(jBC, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 54, 45));

        jBCE.setText("CE");
        jBCE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCEActionPerformed(evt);
            }
        });
        getContentPane().add(jBCE, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 80, 54, 45));

        jB1.setText("1");
        jB1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB1ActionPerformed(evt);
            }
        });
        getContentPane().add(jB1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 54, 45));

        jB2.setText("2");
        jB2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB2ActionPerformed(evt);
            }
        });
        getContentPane().add(jB2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 140, 54, 45));

        jB3.setText("3");
        jB3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB3ActionPerformed(evt);
            }
        });
        getContentPane().add(jB3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 140, 54, 45));

        jB4.setText("4");
        jB4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB4ActionPerformed(evt);
            }
        });
        getContentPane().add(jB4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 54, 45));

        jB5.setText("5");
        jB5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB5ActionPerformed(evt);
            }
        });
        getContentPane().add(jB5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 200, 54, 45));

        jB6.setText("6");
        jB6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB6ActionPerformed(evt);
            }
        });
        getContentPane().add(jB6, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 200, 54, 45));

        jB7.setText("7");
        jB7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB7ActionPerformed(evt);
            }
        });
        getContentPane().add(jB7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, 54, 45));

        jB8.setText("8");
        jB8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB8ActionPerformed(evt);
            }
        });
        getContentPane().add(jB8, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 260, 54, 45));

        jB9.setText("9");
        jB9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB9ActionPerformed(evt);
            }
        });
        getContentPane().add(jB9, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 260, 54, 45));

        jB0.setText("0");
        jB0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB0ActionPerformed(evt);
            }
        });
        getContentPane().add(jB0, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 320, 54, 45));

        jBDividir.setText("/");
        jBDividir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBDividirActionPerformed(evt);
            }
        });
        getContentPane().add(jBDividir, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 320, 54, 45));

        jBPuntoDecimal.setText(".");
        jBPuntoDecimal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBPuntoDecimalActionPerformed(evt);
            }
        });
        getContentPane().add(jBPuntoDecimal, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, 54, 45));

        jBIgual.setText("=");
        jBIgual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBIgualActionPerformed(evt);
            }
        });
        getContentPane().add(jBIgual, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 320, 54, 45));

        jBSumar.setText("+");
        jBSumar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBSumarActionPerformed(evt);
            }
        });
        getContentPane().add(jBSumar, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 140, 54, 45));

        jBMultiplicar.setText("*");
        jBMultiplicar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBMultiplicarActionPerformed(evt);
            }
        });
        getContentPane().add(jBMultiplicar, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 200, 54, 45));

        jBRestar.setText("-");
        jBRestar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBRestarActionPerformed(evt);
            }
        });
        getContentPane().add(jBRestar, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 260, 54, 45));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jB1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB1ActionPerformed
        // TODO add your handling code here:
        jTnumeros.setText(jTnumeros.getText() + "1");
    }//GEN-LAST:event_jB1ActionPerformed

    private void jB2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB2ActionPerformed
        // TODO add your handling code here:
        jTnumeros.setText(jTnumeros.getText() + "2");
    }//GEN-LAST:event_jB2ActionPerformed

    private void jB3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB3ActionPerformed
        // TODO add your handling code here:
        jTnumeros.setText(jTnumeros.getText() + "3");
    }//GEN-LAST:event_jB3ActionPerformed

    private void jB4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB4ActionPerformed
        // TODO add your handling code here:
        jTnumeros.setText(jTnumeros.getText() + "4");
    }//GEN-LAST:event_jB4ActionPerformed

    private void jB5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB5ActionPerformed
        // TODO add your handling code here:
        jTnumeros.setText(jTnumeros.getText() + "5");
    }//GEN-LAST:event_jB5ActionPerformed

    private void jB6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB6ActionPerformed
        // TODO add your handling code here:
        jTnumeros.setText(jTnumeros.getText() + "6");
    }//GEN-LAST:event_jB6ActionPerformed

    private void jB7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB7ActionPerformed
        // TODO add your handling code here:
        jTnumeros.setText(jTnumeros.getText() + "7");
    }//GEN-LAST:event_jB7ActionPerformed

    private void jB8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB8ActionPerformed
        // TODO add your handling code here:
        jTnumeros.setText(jTnumeros.getText() + "8");
    }//GEN-LAST:event_jB8ActionPerformed

    private void jB9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB9ActionPerformed
        // TODO add your handling code here:
        jTnumeros.setText(jTnumeros.getText() + "9");
    }//GEN-LAST:event_jB9ActionPerformed

    private void jB0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB0ActionPerformed
        // TODO add your handling code here:
        jTnumeros.setText(jTnumeros.getText() + "0");
    }//GEN-LAST:event_jB0ActionPerformed

    private void jBCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCActionPerformed
        // TODO add your handling code here:
        limpiarTodo();
    }//GEN-LAST:event_jBCActionPerformed

    private void jBCEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCEActionPerformed
        // TODO add your handling code here:
        limpiar();
    }//GEN-LAST:event_jBCEActionPerformed

    private void jBSumarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBSumarActionPerformed
        // TODO add your handling code here:
        sumar();
    }//GEN-LAST:event_jBSumarActionPerformed

    private void jBMultiplicarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBMultiplicarActionPerformed
        // TODO add your handling code here:
        multiplicar();
    }//GEN-LAST:event_jBMultiplicarActionPerformed

    private void jBRestarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBRestarActionPerformed
        // TODO add your handling code here:
        restar();
    }//GEN-LAST:event_jBRestarActionPerformed

    private void jBDividirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBDividirActionPerformed
        // TODO add your handling code here:
        dividir();
    }//GEN-LAST:event_jBDividirActionPerformed

    private void jBIgualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBIgualActionPerformed
        // TODO add your handling code here:
        igual();
    }//GEN-LAST:event_jBIgualActionPerformed

    private void jBPuntoDecimalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBPuntoDecimalActionPerformed
        // TODO add your handling code here:
        puntoDecimal();
    }//GEN-LAST:event_jBPuntoDecimalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CalculadoraView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CalculadoraView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CalculadoraView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CalculadoraView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CalculadoraView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jB0;
    private javax.swing.JButton jB1;
    private javax.swing.JButton jB2;
    private javax.swing.JButton jB3;
    private javax.swing.JButton jB4;
    private javax.swing.JButton jB5;
    private javax.swing.JButton jB6;
    private javax.swing.JButton jB7;
    private javax.swing.JButton jB8;
    private javax.swing.JButton jB9;
    private javax.swing.JButton jBC;
    private javax.swing.JButton jBCE;
    private javax.swing.JButton jBDividir;
    private javax.swing.JButton jBIgual;
    private javax.swing.JButton jBMultiplicar;
    private javax.swing.JButton jBPuntoDecimal;
    private javax.swing.JButton jBRestar;
    private javax.swing.JButton jBSumar;
    private javax.swing.JButton jButton19;
    private javax.swing.JTextField jTnumeros;
    // End of variables declaration//GEN-END:variables

}
